// <auto-generated />
namespace ThemePark.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PopADMITTED_BY4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PopADMITTED_BY4));
        
        string IMigrationMetadata.Id
        {
            get { return "201904132145311_PopADMITTED_BY4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
